Adding AFD Service Tag Check policy for consumption tier
Azure/api-management-policy-snippets pull request #81
Opened 2022-03-02 17:49 UTC by WillEastbury

2022-03-04 05:59 UTC, VitaliyKurokhtin requested changes

2022-03-04 05:59 UTC, VitaliyKurokhtin commented on examples/CheckInboundIPIsInAFDServiceTagRangeOnConsumptionTier.policy.xml
> +        <cache-lookup-value key="cacheresponse1" variable-name="cacheresponse1" />
Why "1"?

2022-03-04 05:59 UTC, VitaliyKurokhtin commented on examples/CheckInboundIPIsInAFDServiceTagRangeOnConsumptionTier.policy.xml
> +                        return (((int)HostToNetworkOrderShort((short)host) & 0xFFFF) << 16) | ((int)HostToNetworkOrderShort((short)(host >> 16)) & 0xFFFF);
Shouldn't bytes within a word also be rotated?

2022-03-04 05:59 UTC, VitaliyKurokhtin commented on examples/CheckInboundIPIsInAFDServiceTagRangeOnConsumptionTier.policy.xml
> +                }" />
List of strings would be more efficiently stored in a string with a separator, i.e. string1|string2|string3

2022-03-04 05:59 UTC, VitaliyKurokhtin commented on examples/CheckInboundIPIsInAFDServiceTagRangeOnConsumptionTier.policy.xml
> +                            int ipAddr = BitConverter.ToInt32(cidrIPBytes,0);
Doing bit shift operations would be more efficient

2023-04-11 15:22 UTC, adrianhall commented
Closing due to age and lack of response.

2023-04-11 15:22 UTC, closed without merging